version: '3.7'

services:

  redis:
    image: redis
    command: redis-server

  celery:
    build: .
    entrypoint: celery -A StickerShop worker --loglevel=info 

  django:
    build: .
    entrypoint: python3 manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on: 
      - redis
      - celery
