version: '3.7'

services:

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  celery:
    build: .
    image: localhost:5000/shop-project:1.0.0
    restart: always
    entrypoint: celery -A Shop worker --loglevel=info 
    depends_on: 
      - rabbit

  django:
    build: .
    image: localhost:5000/shop-project:1.0.0
    restart: always
    entrypoint: python3 manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on: 
      - rabbit
      - celery

volumes:
  rabbitmq_data:
