version: '3.7'

services:

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  celery:
    build: .
    environment: 
      - BROKER_URL=rabbit
      - SECRET_KEY=fooBar
      - STRIPE_PUBLISHABLE_KEY=fooBar
      - STRIPE_SECRET_KEY=fooBar
      - EMAIL_USERNAME=fooBar
      - EMAIL_PASSWORD=fooBar
    entrypoint: celery -A Shop worker --loglevel=info 
    depends_on: 
      - rabbit

  django:
    build: .
    environment: 
      - BROKER_URL=rabbit
      - SECRET_KEY=fooBar
      - STRIPE_PUBLISHABLE_KEY=fooBar
      - STRIPE_SECRET_KEY=fooBar
      - EMAIL_USERNAME=fooBar
      - EMAIL_PASSWORD=fooBar
    entrypoint: python3 manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on: 
      - rabbit
      - celery

volumes:
  rabbitmq_data:
