apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: 192.168.0.151:5000/shop-project:1.0.0
          imagePullPolicy: Always
          command: ["celery", "-A", "Shop", "worker", "--loglevel=info"]
          ports:
            - containerPort: 80
          env:
            - name: BROKER_URL
              value: rabbitmq
            - name: SECRET_KEY
              value: "fooBar"
            - name: STRIPE_PUBLISHABLE_KEY
              value: "fooBar"
            - name: STRIPE_SECRET_KEY
              value: "fooBar"
            - name: EMAIL_USERNAME
              value: "fooBar"
            - name: EMAIL_PASSWORD
              value: "fooBar"
