# Generated by Django 3.1.1 on 2020-11-08 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201108_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productSize', to='products.productsize'),
        ),
    ]
