# Generated by Django 3.1.1 on 2020-11-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderproduct_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='price',
            new_name='cost',
        ),
    ]
